name: 'capybara-action'
description: 'Capybara is a GitHub Action used to automatically reschedule workflow runs depending on the most carbon efficient time. Capybara also regularly reports on the carbon emissions saved.'
inputs:
  isCapybaraDispatch:
    description: System property required by Capybara backend
    required: true
  github-token:
    description: GITHUB_TOKEN secret
    required: true
  capybaraUrl:
    description: URL for Capybara backend
    required: true
  clientId:
    description: The client id of the repo
    required: true
  workflowId:
    description: The ID of the workflow
    required: true
  repoName:
    description: The name of the repository. The name is not case sensitive
    required: true
  ref:
    description: The git reference for the workflow. The reference can be a branch or tag name
    required: true
  owner:
    description: The account owner of the repository. The name is not case sensitive
    required: true
  durationInMinutes:
    description: An approximate duration of the workflow run*. If not provided, defaults to 5 min
    required: false
  maximumDelayInSeconds:
    description: How long after the schedule start of the run the pipeline can be triggered
    required: true
  location:
    description: The location of the workflow runner
    required: true

outputs:
  bestTimeToStart: # id of output
    description: Best time to start the workflow run
runs:
  using: 'node16'
  main: 'dist/index.js'
